### ISSUE TITLE
Failed to connect - Host is unreachable

### ISSUE THREAD

**Issue by fraksken** [blind-coder/rcmcarddav#185]
The plugin installed fine. The settings menu shows but after inputting all the data I get a white page.
Environment:
roundcube runs in a docker container example.com/webmail
baikal runs in the same docker container under another domain. They both use the same reverse proxy. host: dav.example.com
The docker container of roundcube can ping dav.example.com
Webserver and reverse proxy are nginx

logs:
==> logs/errors <==
[22-Feb-2017 14:25:37 CET] Failed to connect to dav.example.com port 443: Host is unreachable
[22-Feb-2017 14:25:37 CET] PHP Fatal error:  Uncaught Httpful\Exception\ConnectionErrorException: Unable to connect to "https://dav.example.com:443/.well-known/carddav": 7 Failed to connect to dav.example.com port 443: Host is unreachable in /usr/share/nginx/example/webmail/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php:1028
Stack trace:
#0 /usr/share/nginx/example/webmail/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php(204): Httpful\Request->buildResponse(false)
#1 /usr/share/nginx/example/webmail/plugins/carddav/carddav_common.php(185): Httpful\Request->send()
#2 /usr/share/nginx/example/webmail/plugins/carddav/carddav_discovery.php(123): carddav_common->cdfopen('https://dav.exa...', Array, Array)
#3 /usr/share/nginx/example/webmail/plugins/carddav/carddav_discovery.php(93): carddav_discovery->retrieve_addressbooks('/.well-known/ca...', Array)
#4 /usr/share/nginx/example/webmail/plugins/carddav/carddav.php(538): carddav_discovery->find_addressbooks('dav.example.com', 'user@example.com', '{BASE64}KefdTg...')
#5 /usr/share/nginx/example/webmail/ in /usr/share/nginx/example/webmail/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php on line 1028

I thought at first it might be an ssl issue because curl gave errors. But I fixed that and the problem persists.
I have manually added the domain and ip in the hosts file, but the issue persists.
Am I missing something?

**Comment by fraksken** [comment]
I'm sorry for wasting time. This is a docker issue.
If other people face the same problem:
ip route get 172.19.0.0 | awk '{print $4}'
# replace 172.18.0.0 with the ip of the subnet
# paste the result in:
iptables -I INPUT 1 -i <docker device> -j ACCEPT
