### ISSUE TITLE
couldn't connect to host

### ISSUE THREAD

**Issue by writetome** [blind-coder/rcmcarddav#195]
Hello,

when I enter my server URL the error "could not connect to host" appear.
Problem is obviously the port (8443) in the URL:
https://my.domain.net:8443/addressbooks/users/admin/addressbook/

Is there a solution for this?

Error LOG:
[30-May-2017 12:08:14 Europe/Berlin] couldn't connect to host
[30-May-2017 12:08:14 Europe/Berlin] PHP Fatal error:  Uncaught exception 'Httpful\Exception\ConnectionErrorException' with message 'Unable to connect to "https://my.domain.net:8443/addressbooks/users/admin/addressbook/": 7 couldn't connect to host' in /var/www/vhosts/hosting.netcup.net/httpdocs/email/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php:1028
Stack trace:
#0 /var/www/vhosts/hosting.netcup.net/httpdocs/email/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php(204): Httpful\Request->buildResponse(false)
#1 /var/www/vhosts/hosting.netcup.net/httpdocs/email/plugins/carddav/carddav_common.php(185): Httpful\Request->send()
#2 /var/www/vhosts/hosting.netcup.net/httpdocs/email/plugins/carddav/carddav_discovery.php(123): carddav_common->cdfopen('https://my.d...', Array, Array)
#3 /var/www/vhosts/hosting.netcup.net/httpdocs/email/plugins/carddav/carddav_discovery.php(93): carddav_discovery->retrieve_addressbooks('/addressbooks/u...', Array)
#4 /var/www/vhosts/hosting.net in /var/www/vhosts/hosting.netcup.net/httpdocs/email/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php on line 1028

Info:
The CardDav Server is a Synology NAS with a DynDns adress.
With the iPhone, the CardDav Server works perfectly.

thanks for your help
Tobias

**Comment by blind-coder** [comment]
The port should actually be properly handled. Can you enable DEBUG and DEBUG_HTTP in carddav_common.php and try again? There will be additional output in roundcube/logs/carddav

**Comment by writetome** [comment]
This is the log output in roundcube/logs/carddav:
[31-May-2017 10:14:28 +0200]: <2klb7q9n> DISCOVERY: (retrieve_addressbooks) SEARCHING https://my.domain.net:8443/addressbooks/users/admin/addressbook/ (Depth: 0)
[31-May-2017 10:14:28 +0200]: <2klb7q9n> DISCOVERY: (cdfopen) retrieve_addressbooks requesting https://my.domain.net:8443/addressbooks/users/admin/addressbook/ [RL 5]

**Comment by writetome** [comment]
It's clear now. My host has blocked outbound connections to non-standard ports. It's all fine now :-)
