### ISSUE TITLE
php5-curl requires libcurl3

### ISSUE THREAD

**Issue by marcvs** [blind-coder/rcmcarddav#250]
php5-curl requires libcurl3, but that conflucts with libcurl4, installed as a dependency of php7.2-curl.

Regardless of using php7.2-curl and libcurl4  or libcurl3 and php5-curl, I get the following trace.  Probably, because I'm on debian/testing and use php7.2 as a default.

Are there plans to move to php7.2?

```
Stack trace:
#0 /usr/share/roundcube/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php(200): Httpful\Request->_curlPrep()
#1 /usr/share/roundcube/plugins/carddav/carddav_common.php(185): Httpful\Request->send()
#2 /usr/share/roundcube/plugins/carddav/carddav_discovery.php(123): carddav_common->cdfopen('https://hardt-i...', Array, Array)
#3 /usr/share/roundcube/plugins/carddav/carddav_discovery.php(93): carddav_discovery->retrieve_addressbooks('/davical/caldav...', Array)
#4 /usr/share/roundcube/plugins/carddav/carddav.php(539): carddav_discovery->find_addressbooks('https://hardt-i...', 'marcus', '{BASE64}aWh0UmE...')
#5 /usr/share/roundcube/program/lib/Roundcube/rcube_plugin_api.php(440): carddav->cd_save(Array)
#6 /usr/share/roundcube/program/steps/settings/save_prefs.inc(144): rcube_plugin_api->exec_hook('preferences_sav...', Array)
#7 /usr/ in /usr/share/roundcube/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php on line 843
```

**Comment by blind-coder** [comment]
What's the actual error you got? The stack trace itself is not very helpful.

I'm running php7.0 myself and it works fine.

**Comment by mstilkerich** [comment]
No reply - closing.
