### ISSUE TITLE
Doesn't work with 65Mbytes carddav collection.

### ISSUE THREAD

**Issue by 532910** [blind-coder/rcmcarddav#259]
`PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 67155936 bytes) in /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/vendor/nategood/httpful/src/Httpful/Request.php on line 1043`

Increasing memory_limit to 1024M givs:
```
PHP Warning:  SimpleXMLElement::__construct(): Entity: line 1430: parser error : internal error: Huge input lookup in /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_common.php on line 117
PHP Warning:  SimpleXMLElement::__construct(): 8wjfnpp0PI6NEdmbyFhRt5E7N/sP4fmn/InZOUvqAAAAAASUVORK5CYIJpZGVudGljb25fbWFya2VyAA in /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_common.php on line 117
PHP Warning:  SimpleXMLElement::__construct():                                                                                ^ in /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_common.php on line 117
PHP Fatal error:  Uncaught Exception: String could not be parsed as XML in /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_common.php:117
Stack trace:
#0 /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_common.php(117): SimpleXMLElement->__construct('<?xml version='...')
#1 /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_backend.php(729): carddav_common->checkAndParseXML(Array)
#2 /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_backend.php(895): carddav_backend->query_addressbook_multiget(Array)
#3 /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_backend.php(596): carddav_backend->addvcards(Object(SimpleXMLElement))
#4 /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_backend.php(465): carddav_backend->list_records_sync_collection()
#5 /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_backend.php(111): carddav_backend->refreshdb_from_server()
#6 /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav.php(294): card in /srv/www/roundcubemail-1.4-rc1-complete/plugins/carddav/carddav_common.php on line 117
```

**Comment by blind-coder** [comment]
I have added a possible fix in branch issue_259, can you please test that?

**Comment by 532910** [comment]
I confirm that the branch `issue_259` works. Memory limit should still be increased, but it doesn't fails with `PHP Fatal error` and shows contacts and photos correctly.

**Comment by 532910** [comment]
Is any update there?
